# -*- coding: utf-8 -*-
"""CODE-Osteoporosis Produces Detectable Radiographic Texture Changes in Trabecular-Rich Spine Bone Compared to Cortical-Rich Knee Bone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zk3Mh9CTb4mnHwSyUgXyUk9HJp68zfI4

##Setup
"""

import sys
import importlib
import subprocess
from packaging import version

MIN_TORCH = "1.12.0"
MIN_TORCHVISION = "0.13.0"

def install_packages(cuda_index_url=None):
    """
    Installs/updates torch, torchvision, torchaudio.
    If cuda_index_url is provided, pip will use that index (useful to get CUDA-enabled wheels).
    """
    pip_cmd = [sys.executable, "-m", "pip", "install", "-U", "torch", "torchvision", "torchaudio"]
    if cuda_index_url:
        pip_cmd += ["--index-url", cuda_index_url]
    print("[INFO] Running:", " ".join(pip_cmd))
    subprocess.check_call(pip_cmd)
    importlib.invalidate_caches()

def ensure_torch():
    try:
        import torch, torchvision
        tver = torch.__version__
        tvver = torchvision.__version__
        print(f"[INFO] Found torch {tver}, torchvision {tvver}")
        if version.parse(tver) < version.parse(MIN_TORCH) or version.parse(tvver) < version.parse(MIN_TORCHVISION):
            print(f"[INFO] torch/torchvision older than required ({MIN_TORCH}/{MIN_TORCHVISION}). Upgrading now...")
            # OPTIONAL: change cuda_index_url to match your CUDA (eg. cu118 or cu117) if desired
            # e.g. cuda_index_url = "https://download.pytorch.org/whl/cu118"
            install_packages(cuda_index_url=None)
            importlib.reload(torch)
            importlib.reload(torchvision)
            print(f"[INFO] After upgrade: torch {torch.__version__}, torchvision {torchvision.__version__}")
        else:
            print("[INFO] torch/torchvision meet requirements.")
    except Exception as e:
        print("[WARN] Could not import torch/torchvision or version check failed:", e)
        print("[INFO] Installing/Upgrading torch, torchvision, torchaudio now...")
        install_packages(cuda_index_url=None)
        import torch, torchvision
        print(f"[INFO] After install: torch {torch.__version__}, torchvision {torchvision.__version__}")

ensure_torch()


print("\n[NOTE] If this cell performed an installation or upgrade, please RESTART the runtime (Runtime -> Restart runtime) before running subsequent cells.")

# Regular imports for feature extraction workflow
import matplotlib.pyplot as plt
import torch
import torchvision

from torch import nn
from torchvision import transforms

# torchinfo
try:
    from torchinfo import summary
except ImportError:
    print("[INFO] Couldn't find torchinfo... installing it.")
    !pip install -q torchinfo
    from torchinfo import summary

try:
    from going_modular.going_modular import data_setup
except ImportError:
    print("[INFO] Couldn't find going_modular scripts... downloading them from GitHub.")
    !git clone https://github.com/mrdbourke/pytorch-deep-learning
    !mv pytorch-deep-learning/going_modular .
    !rm -rf pytorch-deep-learning
    from going_modular.going_modular import data_setup

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

# Base project path in Google Drive
data_path = Path("/content/drive/MyDrive/ISEF_JSHS/")
image_path = data_path / "Dataset"

# Define dataset subfolders (adjust if your dataset is organized differently)
train_dir = image_path / "Train"
test_dir = image_path / "Test"

print("Train directory:", train_dir)
print("Test directory:", test_dir)

# Transforms for EfficientNet-B0
from torchvision import models

# Use the official EfficientNet-B0 pretrained weights to get correct transforms
weights = models.EfficientNet_B0_Weights.DEFAULT
data_transforms = weights.transforms()

# Now data_transforms will handle resizing, cropping, normalization automatically
print(data_transforms)

from torchvision import datasets

# Load datasets with EfficientNet transforms
train_dataset = datasets.ImageFolder(train_dir, transform=data_transforms)
test_dataset  = datasets.ImageFolder(test_dir,  transform=data_transforms)

print("Train classes:", train_dataset.classes)
print("Test classes:", test_dataset.classes)

# Load pretrained EfficientNet-B0
from torchvision import models

weights = models.EfficientNet_B0_Weights.DEFAULT
model = models.efficientnet_b0(weights=weights).to(device)
model.eval()  # VERY IMPORTANT — evaluation mode (no dropout/batchnorm updates)

print("[INFO] Loaded EfficientNet-B0 in eval mode for feature extraction")

# Print model summary
summary(model=model,
        input_size=(32, 3, 224, 224),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20,
        row_settings=["var_names"]
)

# Freeze EfficientNet weights for feature extraction
for param in model.parameters():
    param.requires_grad = False

import torch
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from torchvision import transforms # Import transforms

# -------- helper: reverse normalization for display --------
def denormalize(tensor, mean, std):
    tensor = tensor.clone().permute(1, 2, 0).numpy()
    tensor = tensor * std + mean
    return np.clip(tensor, 0, 1)

mean = np.array([0.485, 0.456, 0.406])
std  = np.array([0.229, 0.224, 0.225])

# -------- pick 4 samples --------
samples = [
    ("Normal Knee", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Normal Knee/N12.JPEG'),
    ("Normal Spine", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Normal Spine/Healthy2.jpg'),
    ("Osteoporotic Knee", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Osteoporotic Knee/OP3.JPEG'),
    ("Osteoporotic Spine", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Osteoporotic Spine/Spine Osteoporosis 1.jpg')
]

# -------- plot --------
fig, axes = plt.subplots(4, 3, figsize=(10, 12))

# Extract resize_size and crop_size from data_transforms
resize_size = data_transforms.resize_size
crop_size = data_transforms.crop_size

# Create a separate transform for just resizing and cropping
resize_crop_transform = transforms.Compose([
    transforms.Resize(resize_size),
    transforms.CenterCrop(crop_size)
])

for i, (label, path) in enumerate(samples):
    img = Image.open(path)

    # Step 1: Original
    axes[i, 0].imshow(img, cmap='gray')
    axes[i, 0].set_title(f"{label}\nOriginal")
    axes[i, 0].axis('off')

    # Step 2: Resize/Crop (from transform)
    # Apply the new resize_crop_transform
    resized = resize_crop_transform(img)
    axes[i, 1].imshow(resized)
    axes[i, 1].set_title("Resized/Cropped (224×224)")
    axes[i, 1].axis('off')

    # Step 3: Full transform (tensor + normalized)
    tensor_img = data_transforms(img)

    # convert back for display
    norm_img = denormalize(tensor_img, mean, std)

    axes[i, 2].imshow(norm_img)
    axes[i, 2].set_title("Normalized (ImageNet)")
    axes[i, 2].axis('off')

plt.tight_layout()
plt.show()

import numpy as np
from torch.utils.data import DataLoader

def extract_features_with_paths(model, dataset, device):
    model.eval()
    all_features, all_labels, all_sites, all_paths = [], [], [], []
    loader = DataLoader(dataset, batch_size=32, shuffle=False)

    with torch.no_grad():
        for inputs, labels in loader:
            inputs = inputs.to(device)
            feats = model.features(inputs)
            pooled = model.avgpool(feats)
            flat = torch.flatten(pooled, 1)
            all_features.append(flat.cpu().numpy())
            all_labels.append(labels.cpu().numpy())

        # record file paths for site detection
        paths = [p for p, _ in dataset.samples]

    # Stack features
    features = np.vstack(all_features)
    labels = np.concatenate(all_labels)

    # Map folder-based labels to condition + site
    conditions, sites = [], []
    for path in paths:
        path_lower = path.lower()
        if "normal" in path_lower:
            conditions.append(0)  # Normal
        elif "osteo" in path_lower:
            conditions.append(1)  # Osteoporotic
        else:
            conditions.append(-1)

        if "knee" in path_lower:
            sites.append("knee")
        elif "spine" in path_lower:
            sites.append("spine")
        else:
            sites.append("unknown")

    return features, np.array(conditions), np.array(sites), paths

# Extract from TRAIN and TEST
train_features, train_conditions, train_sites, train_paths = extract_features_with_paths(model, train_dataset, device)
test_features, test_conditions, test_sites, test_paths     = extract_features_with_paths(model, test_dataset,  device)

# Merge train+test
features   = np.vstack([train_features, test_features])
conditions = np.concatenate([train_conditions, test_conditions])
sites      = np.concatenate([train_sites, test_sites])
file_paths = train_paths + test_paths

print("Total samples:", len(file_paths))
print("Unique sites:", set(sites))
print("Conditions check (0=Normal,1=Osteo):", np.unique(conditions, return_counts=True))

import numpy as np

def cohens_d(x, y):
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2

    pooled_std = np.sqrt(
        ((nx - 1) * np.var(x, ddof=1) + (ny - 1) * np.var(y, ddof=1)) / dof
    )

    return (np.mean(x) - np.mean(y)) / pooled_std


for site in ["spine", "knee"]:
    mask = (sites == site)
    if mask.sum() == 0:
        continue

    X_site = features[mask]
    y_site = conditions[mask]

    pca = PCA(n_components=2)
    Xp = pca.fit_transform(X_site)

    group0 = Xp[y_site == 0, 0]  # Normal
    group1 = Xp[y_site == 1, 0]  # Osteo

    if len(group0) == 0 or len(group1) == 0:
        continue

    # t-test
    t_stat, p_val = ttest_ind(group1, group0, equal_var=False)

    # Cohen's d
    d = cohens_d(group1, group0)

    print(f"\nSite: {site.capitalize()}")
    print(f"  Mean Normal: {group0.mean():.3f}")
    print(f"  Mean Osteo: {group1.mean():.3f}")
    print(f"  t = {t_stat:.3f}, p = {p_val:.5f}")
    print(f"  Cohen's d = {d:.3f}")

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# -------- pick same 4 samples --------
# -------- pick 4 samples --------
samples = [
    ("Normal Knee", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Normal Knee/N12.JPEG'),
    ("Normal Spine", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Normal Spine/Healthy2.jpg'),
    ("Osteoporotic Knee", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Osteoporotic Knee/OP3.JPEG'),
    ("Osteoporotic Spine", '/content/drive/MyDrive/ISEF_JSHS/Dataset/Train/Osteoporotic Spine/Spine Osteoporosis 1.jpg')
]


# -------- extract features for each --------
feature_vectors = []

for label, path in samples:
    img = Image.open(path)
    x = data_transforms(img).unsqueeze(0).to(device)

    with torch.no_grad():
        feats = model.features(x)
        pooled = model.avgpool(feats)
        flat = torch.flatten(pooled, 1)

    feature_vectors.append((label, flat.cpu().numpy().flatten()))

# -------- plot subset of features --------
plt.figure(figsize=(10, 6))

for label, vec in feature_vectors:
    subset = vec[:100]  # first 100 features
    plt.plot(subset, label=label)

plt.xlabel("Feature Index")
plt.ylabel("Feature Value")
plt.title("Subset of Extracted CNN Features (First 100 Dimensions)")
plt.legend()
plt.show()

from sklearn.decomposition import PCA
from scipy.stats import ttest_ind

for site in ["spine", "knee"]:
    mask = (sites == site)
    if mask.sum() == 0:
        continue

    X_site = features[mask]
    y_site = conditions[mask]  #  Normal vs Osteo

    pca = PCA(n_components=2)
    Xp = pca.fit_transform(X_site)

    group0 = Xp[y_site == 0, 0]  # Normal
    group1 = Xp[y_site == 1, 0]  # Osteo

    print(f"\nSite: {site.capitalize()} | N={len(y_site)}")
    print(f"  Samples Normal={len(group0)}, Osteo={len(group1)}")

    if len(group0) == 0 or len(group1) == 0:
        print("  Skipping t-test (missing one group)")
        continue

    t_stat, p_val = ttest_ind(group1, group0, equal_var=False)

    print(f"  PC1 mean (Normal): {group0.mean():.3f}, PC1 mean (Osteo): {group1.mean():.3f}")
    print(f"  T-test: t={t_stat:.3f}, p={p_val:.5f}")

    plt.figure(figsize=(6,5))
    plt.scatter(Xp[y_site==0,0], Xp[y_site==0,1], alpha=0.5, label="Normal", c="blue")
    plt.scatter(Xp[y_site==1,0], Xp[y_site==1,1], alpha=0.5, label="Osteoporosis", c="red")
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.title(f"PCA of {site.capitalize()} Radiographs")
    plt.legend()
    plt.savefig(f"/content/drive/MyDrive/ISEF_JSHS/pca_{site}.png", dpi=200)
    plt.show()

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Ellipse

def plot_ellipse(x, y, ax, color, label):
    cov = np.cov(x, y)
    if cov.shape != (2, 2):
        return

    vals, vecs = np.linalg.eigh(cov)
    order = vals.argsort()[::-1]
    vals, vecs = vals[order], vecs[:, order]

    theta = np.degrees(np.arctan2(*vecs[:,0][::-1]))
    width, height = 2 * np.sqrt(vals)

    ellipse = Ellipse(
        (np.mean(x), np.mean(y)),
        width=width,
        height=height,
        angle=theta,
        edgecolor=color,
        facecolor='none',   # 🔥 outline only (fixes misleading shading)
        linestyle='--',
        linewidth=2,
        label=label
    )
    ax.add_patch(ellipse)

for site in ["spine", "knee"]:
    mask = (sites == site)
    if mask.sum() == 0:
        continue

    X_site = features[mask]
    y_site = conditions[mask]

    pca = PCA(n_components=2)
    Xp = pca.fit_transform(X_site)

    group0 = Xp[y_site == 0]  # Normal
    group1 = Xp[y_site == 1]  # Osteo

    plt.figure(figsize=(6,5))
    ax = plt.gca()

    # Scatter
    ax.scatter(group0[:,0], group0[:,1], alpha=0.6, label="Normal")
    ax.scatter(group1[:,0], group1[:,1], alpha=0.6, label="Osteoporosis")

    # Centroids
    mean0 = group0.mean(axis=0)
    mean1 = group1.mean(axis=0)

    ax.scatter(*mean0, marker='X', s=150, label="Normal Centroid")
    ax.scatter(*mean1, marker='X', s=150, label="Osteo Centroid")

    # Ellipses ONLY for spine (avoid misleading knee plot)
    if site == "spine":
        plot_ellipse(group0[:,0], group0[:,1], ax, color='blue', label="Normal Spread")
        plot_ellipse(group1[:,0], group1[:,1], ax, color='orange', label="Osteo Spread")

    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")
    ax.set_title(f"PCA of {site.capitalize()} Radiographs")
    ax.legend()
    plt.show()

import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

positions = []
labels = []
pos = 0

for site in ["spine", "knee"]:
    mask = (sites == site)
    if mask.sum() == 0:
        continue

    X_site = features[mask]
    y_site = conditions[mask]

    pca = PCA(n_components=2)
    Xp = pca.fit_transform(X_site)

    pc1 = Xp[:, 0]

    normal_vals = pc1[y_site == 0]
    osteo_vals  = pc1[y_site == 1]

    for group_name, vals in [("Normal", normal_vals), ("Osteo", osteo_vals)]:
        mean = vals.mean()
        std  = vals.std()

        # Bar
        plt.bar(pos, mean, yerr=std, capsize=5)

        # 🔥 Raw data points (critical improvement)
        jitter = np.random.normal(pos, 0.05, size=len(vals))
        plt.scatter(jitter, vals, alpha=0.5)

        labels.append(f"{site.capitalize()}\n{group_name}")
        positions.append(pos)
        pos += 1

plt.xticks(positions, labels)
plt.ylabel("PC1 Value")
plt.title("PC1 Distribution with Mean ± Standard Deviation")
plt.show()